default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

  - repo: local
    hooks:
      - id: 'nixpkgs-fmt'
        name: 'nixpkgs-fmt'
        description: 'Format nix code with nixpkgs-fmt'
        entry: 'nixpkgs-fmt'
        language: 'system'
        files: '\.nix$'
        always_run: true

  - repo: git://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        args: ["--format=tty", "--shell=bash"]
        files: ^.envrc$
        name: Lint .envrc
        types: [text]
