# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/Baozisoftware/qrcode-terminal-go";
    fetch = {
      type = "git";
      url = "https://github.com/Baozisoftware/qrcode-terminal-go";
      rev = "c0650d8dff0f053901ff16185217b950d5e7743c";
      sha256 = "166h9zy9y7ygayhybg7d080hpdcf1mvkf3rwnq5lqg8i3cg71s7b";
    };
  }
  {
    goPackagePath = "github.com/btcsuite/btcd";
    fetch = {
      type = "git";
      url = "https://github.com/btcsuite/btcd";
      rev = "875b51c9fb83e5521ef5b4f8c9c522126baa2041";
      sha256 = "1f7k9i6hrbxhaxaqf9qjsj9w14xvdq1fa6br0v1cnr71jljp5rfm";
    };
  }
  {
    goPackagePath = "github.com/btcsuite/btclog";
    fetch = {
      type = "git";
      url = "https://github.com/btcsuite/btclog";
      rev = "84c8d2346e9fc8c7b947e243b9c24e6df9fd206a";
      sha256 = "02dl46wcnfpg9sqvg0ipipkpnd7lrf4fnvb9zy56jqa7mfcwc7wk";
    };
  }
  {
    goPackagePath = "github.com/btcsuite/btcutil";
    fetch = {
      type = "git";
      url = "https://github.com/btcsuite/btcutil";
      rev = "6065135ba824dc2b89d4da75699dcb2885bc3e2a";
      sha256 = "11lj3afz2r9lgndx6xwafkmark0a3pk3sfl1sgzh847fgymqwgzn";
    };
  }
  {
    goPackagePath = "github.com/glendc/go-external-ip";
    fetch = {
      type = "git";
      url = "https://github.com/glendc/go-external-ip";
      rev = "c872357d968e33d5d9c47ea2c603f3b411150ecc";
      sha256 = "1h9cdhab4fapa2p1r8sgl1pxv4qi1zskw8x0pj93a81y03zzr2l1";
    };
  }
  {
    goPackagePath = "github.com/jessevdk/go-flags";
    fetch = {
      type = "git";
      url = "https://github.com/jessevdk/go-flags";
      rev = "c0795c8afcf41dd1d786bebce68636c199b3bb45";
      sha256 = "0xsmr17mrpm9kx34zfzzirwy0n459h975x49p41fs2f6ly6lk9vp";
    };
  }
  {
    goPackagePath = "github.com/lightningnetwork/lnd";
    fetch = {
      type = "git";
      url = "https://github.com/lightningnetwork/lnd";
      rev = "8cb1276dbf0bfd9fcbf599df87a43238e599eaac";
      sha256 = "0h7v3225mm6vq24rrgrc54kxvg37pg624mxrsbpnp38kgacc5w4i";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "f6c00982823144337e56cdb71c712eaac151d29c";
      sha256 = "08y5c01bvyqxraj3wc0di80gbp87178rsshb74x0p3m7wwfv82l3";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "cb30d6282491c185f77d9bec5d25de1bb61a06bc";
      sha256 = "0v59mv94acd2m72q8adhigxkx1vn38l5h0d8hp0nxga2v9f3v8kd";
    };
  }
  {
    goPackagePath = "github.com/miekg/dns";
    fetch = {
      type = "git";
      url = "https://github.com/miekg/dns";
      rev = "50b4756e47a1e69825c82175d5c1fafc9109cda3";
      sha256 = "0cdcrsdipqs61aa695nqnzrk9mhc2aql1n7hj21w8snyv9cr9q5i";
    };
  }
  {
    goPackagePath = "github.com/skip2/go-qrcode";
    fetch = {
      type = "git";
      url = "https://github.com/skip2/go-qrcode";
      rev = "da1b6568686e89143e94f980a98bc2dbd5537f13";
      sha256 = "0pghd6y2x8a5fqy4rjn4d8j5jcslb236naycdza5an7vyvinsgs9";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "948cd5f35899cbf089c620b3caeac9b60fa08704";
      sha256 = "05ym028qsqkh0ba9bwny3g25yaggm0brdwpjd6k3fx5h0aqkiwh1";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "5ccada7d0a7ba9aeb5d3aca8d3501b4c2a509fec";
      sha256 = "0bdwdxy2gz48icnh023r5fga3z4x6c8gry8jlfjqr5w12y3s281g";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "ddb9806d33aed8dbaac1cd6f1cba58952e87f933";
      sha256 = "02q932g2pf9pyk0z3s3sqb1aqd569f6pwxyx3gk3k5xqlwwy7z5v";
    };
  }
]
